import type { Country, DiseaseType, Evolution, Achievement } from "./types";

export const DISEASE_TYPES: DiseaseType[] = [
  {
    id: "bacteria",
    name: "Capybacteria",
    emoji: "🦠",
    tagline: "Balanced. Adapts to climates well.",
    startingDna: 4,
    baseInfectivity: 1,
    baseSeverity: 1,
    baseLethality: 1,
    cureSpeedMod: 1,
    mutationRate: 0.02,
    notes: "The starter strain. A capybara sneezed once.",
  },
  {
    id: "virus",
    name: "Abhayrus",
    emoji: "🧬",
    tagline: "Mutates uncontrollably. Hard to control.",
    startingDna: 4,
    baseInfectivity: 1.1,
    baseSeverity: 1.1,
    baseLethality: 1,
    cureSpeedMod: 1.1,
    mutationRate: 0.12,
    unlockBeatType: "bacteria",
    notes: "Constantly evolves on its own (sometimes badly).",
  },
  {
    id: "fungus",
    name: "Edward's Spores",
    emoji: "🍄",
    tagline: "Spreads slowly. Hard to detect.",
    startingDna: 5,
    baseInfectivity: 0.7,
    baseSeverity: 0.6,
    baseLethality: 0.9,
    cureSpeedMod: 0.85,
    mutationRate: 0.03,
    unlockBeatType: "virus",
    notes: "Top-hat spores. Believed to make hosts smarter.",
  },
  {
    id: "parasite",
    name: "Daniel's Worm",
    emoji: "🪱",
    tagline: "Low symptoms. Cure speed cut.",
    startingDna: 5,
    baseInfectivity: 0.85,
    baseSeverity: 0.4,
    baseLethality: 0.7,
    cureSpeedMod: 0.7,
    mutationRate: 0.04,
    unlockBeatType: "fungus",
    notes: "Lives quietly inside hosts, sipping coca cola.",
  },
  {
    id: "prion",
    name: "Austen Prion",
    emoji: "🧠",
    tagline: "Almost invisible. Cure resets.",
    startingDna: 6,
    baseInfectivity: 0.5,
    baseSeverity: 0.3,
    baseLethality: 0.6,
    cureSpeedMod: 0.5,
    mutationRate: 0.01,
    unlockBeatType: "parasite",
    notes: "Folds proteins wrong. Folds your save file wrong.",
  },
  {
    id: "nano",
    name: "Arthur-Bot Swarm",
    emoji: "🤖",
    tagline: "Detected from day one. Race the cure.",
    startingDna: 8,
    baseInfectivity: 1.2,
    baseSeverity: 1,
    baseLethality: 1.2,
    cureSpeedMod: 1.4,
    mutationRate: 0.05,
    unlockBeatType: "prion",
    notes: "The world is already trying to shut you off.",
  },
  {
    id: "bio",
    name: "Capybara Bio-Weapon",
    emoji: "☣️",
    tagline: "Insanely lethal. Burns out without symptoms.",
    startingDna: 10,
    baseInfectivity: 1,
    baseSeverity: 1.5,
    baseLethality: 2.5,
    cureSpeedMod: 1.2,
    mutationRate: 0.06,
    unlockBeatType: "nano",
    notes: "Designed in a lab by William. Very impatient.",
  },
];

export const EVOLUTIONS: Evolution[] = [
  // TRANSMISSION
  { id: "air1", name: "Airborne 1", category: "transmission", cost: 6, description: "Coughs spread infection.", infectivity: 0.6, hot: -0.05 },
  { id: "air2", name: "Airborne 2", category: "transmission", cost: 10, description: "Long-distance droplets.", infectivity: 1.0, requires: ["air1"] },
  { id: "water1", name: "Water 1", category: "transmission", cost: 6, description: "Infects water supply.", infectivity: 0.6, humid: 0.1 },
  { id: "water2", name: "Water 2", category: "transmission", cost: 10, description: "Survives water treatment.", infectivity: 1.1, requires: ["water1"] },
  { id: "rodent", name: "Rodent 1", category: "transmission", cost: 8, description: "Carried by rodents (and capybaras).", infectivity: 0.8, poor: 0.15 },
  { id: "insect", name: "Insect 1", category: "transmission", cost: 8, description: "Carried by mosquitoes.", infectivity: 0.7, hot: 0.15, humid: 0.1 },
  { id: "livestock", name: "Livestock 1", category: "transmission", cost: 7, description: "Spreads through farms.", infectivity: 0.7, poor: 0.05 },
  { id: "blood1", name: "Blood 1", category: "transmission", cost: 5, description: "Blood contact infection.", infectivity: 0.4 },
  { id: "extreme_bio", name: "Extremophile", category: "transmission", cost: 5, description: "Survives all climates.", hot: 0.2, cold: 0.2, arid: 0.2, humid: 0.2 },

  // SYMPTOMS
  { id: "cough", name: "Coughing", category: "symptom", cost: 3, description: "+infectivity, slight detection.", infectivity: 0.5, severity: 0.2 },
  { id: "sneeze", name: "Sneezing", category: "symptom", cost: 4, description: "Big airborne boost.", infectivity: 0.8, severity: 0.3, requires: ["cough"] },
  { id: "rash", name: "Rash", category: "symptom", cost: 3, description: "Annoying. Mild severity.", severity: 0.3, hot: 0.05 },
  { id: "fever", name: "Fever", category: "symptom", cost: 4, description: "Hot bodies cook the cure slower.", severity: 0.4, drugResist: 0.05, hot: -0.05 },
  { id: "vomiting", name: "Vomiting", category: "symptom", cost: 5, description: "Spreads via fluids.", infectivity: 0.4, severity: 0.5, requires: ["fever"] },
  { id: "diarrhea", name: "Capybariarrhea", category: "symptom", cost: 5, description: "Water transmission boosted.", infectivity: 0.5, severity: 0.5, humid: 0.05 },
  { id: "insomnia", name: "Insomnia", category: "symptom", cost: 5, description: "Hosts make poor decisions.", severity: 0.4 },
  { id: "paranoia", name: "Paranoia", category: "symptom", cost: 6, description: "Hosts hoard groceries, spread germs.", infectivity: 0.4, severity: 0.6, requires: ["insomnia"] },
  { id: "seizures", name: "Seizures", category: "symptom", cost: 7, description: "Severe. Lethality up.", severity: 0.7, lethality: 0.7, requires: ["fever"] },
  { id: "coma", name: "Coma", category: "symptom", cost: 9, description: "Hosts slow cure research.", severity: 1.0, lethality: 1.0, drugResist: 0.1, requires: ["seizures"] },
  { id: "organ_failure", name: "Total Organ Failure", category: "symptom", cost: 14, description: "EXTREMELY lethal.", severity: 1.5, lethality: 3.0, requires: ["coma"] },
  { id: "necrosis", name: "Necrosis", category: "symptom", cost: 18, description: "The dead infect more dead.", lethality: 4.0, infectivity: 0.5, requires: ["organ_failure"] },

  // ABILITIES
  { id: "cold1", name: "Cold Resist 1", category: "ability", cost: 6, description: "Survives in cold climates.", cold: 0.4 },
  { id: "cold2", name: "Cold Resist 2", category: "ability", cost: 10, description: "Thrives in arctic.", cold: 0.6, requires: ["cold1"] },
  { id: "hot1", name: "Heat Resist 1", category: "ability", cost: 6, description: "Survives in hot climates.", hot: 0.4 },
  { id: "hot2", name: "Heat Resist 2", category: "ability", cost: 10, description: "Thrives in deserts.", hot: 0.6, arid: 0.4, requires: ["hot1"] },
  { id: "drug1", name: "Drug Resist 1", category: "ability", cost: 8, description: "Slows cure progress.", drugResist: 0.15, rich: 0.1 },
  { id: "drug2", name: "Drug Resist 2", category: "ability", cost: 14, description: "Cure researchers cry.", drugResist: 0.3, rich: 0.15, requires: ["drug1"] },
  { id: "genetic_hard", name: "Genetic Hardening 1", category: "ability", cost: 7, description: "Cure research reset penalty.", drugResist: 0.1 },
  { id: "genetic_hard2", name: "Genetic Hardening 2", category: "ability", cost: 12, description: "More cure pain.", drugResist: 0.2, requires: ["genetic_hard"] },
  { id: "genetic_reshuf", name: "Genetic ReShuffle", category: "ability", cost: 15, description: "Big cure setback.", drugResist: 0.4, requires: ["genetic_hard2"] },
  { id: "environ", name: "Environmental Hardening", category: "ability", cost: 8, description: "Resists all climates.", hot: 0.2, cold: 0.2, humid: 0.2, arid: 0.2 },
];

// Full 175-country world (auto-generated from world-atlas).
export { COUNTRIES } from "./countries.generated";

// Legacy unused (kept for type compat if referenced elsewhere)
function _unusedMake(rows: any[]): Country[] {
  return rows.map(([id, name, emoji, pop, climate, wealth, air, sea, borders]) => ({
    id, name, emoji, population: pop, climate, wealth,
    hasAirport: air, hasSeaport: sea, borders,
    infected: 0, dead: 0, cured: 0,
    airportOpen: true, seaportOpen: true, bordersOpen: true,
    awareness: 0,
  }));
}

export const ACHIEVEMENTS: Achievement[] = [
  { id: "first_blood", name: "First Blood", emoji: "🩸", description: "Cause your first death." },
  { id: "patient_zero", name: "Patient Zero", emoji: "🧫", description: "Infect your first country." },
  { id: "globetrotter", name: "Globetrotter", emoji: "✈️", description: "Infect 10 countries." },
  { id: "extinction", name: "Extinction", emoji: "💀", description: "Wipe out humanity." },
  { id: "speedrun", name: "Speedrun", emoji: "⚡", description: "Win in under 200 days." },
  { id: "silent_killer", name: "Silent Killer", emoji: "🤫", description: "Win without ever evolving a symptom." },
  { id: "cure_loser", name: "Mid", emoji: "💊", description: "Lose to the cure." },
  { id: "frozen_strain", name: "Frozen Strain", emoji: "🧊", description: "Infect Greenland AND Iceland." },
  { id: "all_types", name: "Strain Master", emoji: "🏆", description: "Win with every disease type." },
];
